version: "3.8"
services:
  webapi:
    image: PersonalManagement/api:latest
    restart: always
    build: 
      context: .
      dockerfile: api/Dockerfile
    environment:
      - ASPNETCORE_HTTPS_PORT=6011
      - ASPNETCORE_ENVIRONMENT=Docker
    ports:
      - 6010:8080
      - 6011:8081
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge