version: '3.9'

services:
  personal_management_api:
    image: ${DOCKER_REGISTRY-}personal_management_api
    build: 
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
    networks:
      - mynetwork

  personal_management_frontend:
    image: ${docker_registry-}personal_management_frontend
    build: 
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "5001:81"
    environment:
      - aspnetcore_environment=production
      - aspnetcore_urls=http://+:81
    volumes:
      - data-protection-keys:/app/DataProtectionKeys
    networks:
      - mynetwork
      
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - personal_management_api
      - personal_management_frontend
    networks:
      - mynetwork

volumes:
  data-protection-keys:
  
networks:
  mynetwork:
    driver: bridge