version: '3.4'

services:
  personal_management_api:
    image: ${DOCKER_REGISTRY-}personal_management_api
    build: api/
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
# version: "3.8"
# services:
  # webapi:
    # image: PersonalManagement/api:latest
    # restart: always
    # build: 
      # context: .
      # dockerfile: api/Dockerfile
    # environment:
      # - ASPNETCORE_HTTPS_PORT=6011
      # - ASPNETCORE_ENVIRONMENT=Docker
    # ports:
      # - 6010:8080
      # - 6011:8081
    # networks:
      # - mynetwork

# networks:
  # mynetwork:
    # driver: bridge