version: '3.4'

services:
  personal_management_api:
    image: ${DOCKER_REGISTRY-}personal_management_api
    build: api/
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80

  personal_management_frontend:
    image: ${DOCKER_REGISTRY-}personal_management_frontend
    build: /
    ports:
      - "5001:81"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:81
    depends_on:
      - personal_management_api
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge